CC = gcc
all : threadCooperation

threadCooperation :   threadCooperation.c
	$(CC) -o threadCooperation threadCooperation.c -l pthread

clean:
	rm -rf *.o threadCooperation                                       
